### ISSUE TITLE
Type is not required, but validators.py thinks it should be

### ISSUE THREAD

**Issue by RHeynsZa** [hh-h/aiohttp-swagger3#113]
As per the swagger [docs](https://swagger.io/docs/specification/data-models/data-types/#any)

> A schema without a type matches any data type – numbers, strings, objects, and so on. {} is shorthand syntax for an arbitrary-type schema:

https://github.com/hh-h/aiohttp-swagger3/blob/705ee7757272b7abd0b801ad38a5b151f68a822a/aiohttp_swagger3/validators.py#L678

**Comment by hh-h** [comment]
Hi! Thanks for pointing out the inconsistency, although it contradicts the scheme, it is too rare a use case. I don't see cases for accepting any possible type by API. But I'm open to considering a PR, shouldn't be too much work there. Thank you.
