### ISSUE TITLE
Duplicate library

### ISSUE THREAD

**Issue by Alexei-Kornienko** [hh-h/aiohttp-swagger3#12]
Hi, there is already a pretty nice library here - https://github.com/cr0hn/aiohttp-swagger/
It does basically the same thing. Have you considered joining forces instead of making a duplicate library?

**Comment by hh-h** [comment]
Hello, when I created the library, his project looked like abandoned (still looks, 27 issues/11 PRs without review). Second, I don't like his license. Third, the main focus of this library is validation, so it's the same, but with validation=False, check the README for more info

**Comment by Alexei-Kornienko** [comment]
Hi, thanks for the update.
