### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#24]
Hello,

Could you please create tags ? It would be useful for packager to get latest "stable" version.
I known it's also on PyPi but it misses examples and tests which are definitely useful.

Regards,

**Comment by hh-h** [comment]
Hey! That's not so hard, but I want to understand use cases (to widen my horizons)

**Comment by eLvErDe** [comment]
Let's imagine I'd like to upload your package to Debian archive, I need a tarball of 0.2.4 release.
I can't use PyPi one because I want to run unittests during build.

**Comment by hh-h** [comment]
Thanks. I'll read about GitHub releases and tags.

**Comment by hh-h** [comment]
Added last 3 releases, enjoy! :)
