### ISSUE TITLE
Customize Swagger-UI

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#30]
Hello,

I like to be able to pass a few options to Swagger-UI (JS code) to change it's look.
With aiohttp_swagger, I dirty-patched it like this:

[Swagger-UI index.html to merge JS object representing options](https://github.com/eLvErDe/aiohttp-swagger/blob/39687734726ac72067f4e77209440757925dd6f2/aiohttp_swagger/swagger_ui/index.html#L49)
[Serve index.html as str and format it to include serialized options](https://github.com/eLvErDe/aiohttp-swagger/blob/39687734726ac72067f4e77209440757925dd6f2/aiohttp_swagger/__init__.py#L98)

With this I can pass (e.g) the following options to UI:
bundle_params = {"layout": "BaseLayout", "defaultModelExpandDepth": 5}

Adam.

**Comment by hh-h** [comment]
I'm gonna put it together with my thoughts and think of something :)

**Comment by hh-h** [comment]
#37
