### ISSUE TITLE
Consider ReDoc as a replacement for SwaggerUI ?

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#33]
Hi hh-h,

Have you considered this ? SwaggerUI is pretty much dead and still does not implement AnyOf, AllOf correctly...

Adam

**Comment by hh-h** [comment]
Hi, Adam!

No, I didn't search for alternatives of swagger UI, we're OK with its functionality. 
I wouldn't call swaggerUI dead, it's under active development, see https://github.com/swagger-api/swagger-ui/releases

As for ReDoc, at first glance, it looks nice, but there can be some problems with integration to the library due to React.

**Comment by eLvErDe** [comment]
Look at the commits, it's is dead. All released are just triggered by CI updating node embedded libraries to fix security issues.
Btw, SwaggerUI is react based too !
In the meanwhile I rebuilt SwaggerUI to include a pull request adding proper oneOf support as well as discriminator. I'll do more testing tonight but if you're interested in you could include this version in your python module (or build your own it's pretty straightforward)

Adam

**Comment by hh-h** [comment]
Still, I wouldn't call it dead. Maybe stable?
There's no chance that I'll include custom swagger UI. Please read [CONTRIBUTING.md](github.com/swagger-api/.github/blob/master/CONTRIBUTING.md) and create PR against swagger UI repo, after it merged I can bump swagger UI in the library.

**Comment by eLvErDe** [comment]
That's the point of all PR. SwaggerUI team does not merge any PR ;-)
But anyway, it was just a suggestion I'll maintain my forked version anyway (I DO need proper documentation of oneOf / discriminator).

Regards

**Comment by hh-h** [comment]
I'll add ReDoc as a second UI in a future release

**Comment by hh-h** [comment]
I started to deeply look at it and realized that ReDoc doesn't have "Try it now/API console" feature, whatever that called. This feature is crucial for us as for many people who use swagger UI. I just wanted to share findings :)

**Comment by hh-h** [comment]
Please, try 0.3.5

**Comment by eLvErDe** [comment]
Oh nice :) I'll try to give it a shot by the end of the week
