### ISSUE TITLE
Optional authentication

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#36]
Hello hh-h,

Sorry for one more request but I ported one big API to your module yesterday and I had an issue.
I have a couple of routes that return minimal output in not JWT auth is provided, and enhanced output if token is provided. I did not manage to do this with your module. It's not a big deal at the moment but I could be a problem at some point and would require me to duplicate the route to workaround the issue.

It seems OpenAPI allow such setup by adding an empty objects in security list definitions for the route but aiohttp_swagger3 refuses that.

See: https://github.com/OAI/OpenAPI-Specification/issues/14

Best regards, Adam.

**Comment by hh-h** [comment]
Hey Adam,

First of all, feel free to create as many issues as you want :)

So, the scheme should be like this, am I correct?
```yaml
security:
  - {}
  - bearer
```

BR

**Comment by eLvErDe** [comment]
According to the link yes, looks weird but it seems OpenAPI allows it

**Comment by hh-h** [comment]
#37
