### ISSUE TITLE
data.parameters[0] must be valid exactly by one of oneOf definition since upgrade from 0.2.5

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#48]
```
  File "/usr/lib/python3/dist-packages/aiohttp/web_urldispatcher.py", line 1133, in add_routes
    route_def.register(self)
  File "/usr/lib/python3/dist-packages/aiohttp/web_routedef.py", line 64, in register
    reg(self.path, self.handler, **self.kwargs)
  File "/usr/lib/python3/dist-packages/aiohttp_swagger3/swagger.py", line 179, in add_get
    return self.add_route(hdrs.METH_GET, path, handler, name=name, **kwargs)
  File "/usr/lib/python3/dist-packages/aiohttp_swagger3/swagger_docs.py", line 138, in add_route
    validate=need_validation,
  File "/usr/lib/python3/dist-packages/aiohttp_swagger3/swagger_docs.py", line 78, in _wrap_handler
    self.spec_validate(self.spec)
  File "<string>", line 63, in validate
  File "<string>", line 2232, in validate___definitions_paths
  File "<string>", line 390, in validate___definitions_pathitem
  File "<string>", line 460, in validate___definitions_operation
fastjsonschema.exceptions.JsonSchemaException: data.parameters[0] must be valid exactly by one of oneOf definition
```

It used to work just fine and I don't see what is wrong in my YAML doc. Any hint would be appreciated !

Regards,

**Comment by hh-h** [comment]
Hi, unfortunately, without the scheme I cannot help at all. If you have a huge amount of routes and have no idea what happened, then you can "hack" library, adding some prints :)
For example: either add `print(path)` before this statement `return self.add_route(hdrs.METH_GET, path, handler, name=name, **kwargs)` or add `print(self.spec)` before `self.spec_validate(self.spec)`, and share results with me, I'll try to help :)

**Comment by eLvErDe** [comment]
Yup, I was actually doing this, dumping the JSON before it crashes and it is valid if I check online.

Can you share a direct email address so I send you the dumped spec ?

**Comment by hh-h** [comment]
You can find it in setup.py file.

**Comment by eLvErDe** [comment]
Hi,

Ok I digged deeper and finally figured out: *required: true" is now mandatory on path parameter, while it was working just fine before you moved to fastjsonschema. Also I'm pretty sure it was an error with Swagger, as it's pretty obvious path fragment are required :D
Anyway, it's working again but hopefully this ticket might help someone else facing the same issue.

Regards, Adam.

**Comment by hh-h** [comment]
The openapi-spec-validation library was too slow and too lax, also, it uses own schema to validate against. When I switched to fastjsonschema, I started to use schema from OpenAPI3 official repository. As you can see [here](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json#L1173) `required` is required for path parameter. 
I'm glad that you've figured out!
Cheers

**Comment by eLvErDe** [comment]
I totally support moving to fastjsonschema. 
Btw, I started upgrading tonight so I'll test shinny new features soon :) thanks
