### ISSUE TITLE
Raise custom exception when validation fails

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#49]
Hello,

Would you consider raising a custom exception (that could inherit from badrequest) instead of using built-in aiohttp 400 error ?

That would allow users to implement a custom middleware Implementing specific validation error behavior.

Also you could consider adding a prop containing deserialized errors object.

https://github.com/hh-h/aiohttp-swagger3/blob/5a98c4420a56451dff0a2b4638f95d0288637ddd/aiohttp_swagger3/swagger_route.py#L219

Regards, Adam

**Comment by hh-h** [comment]
Hi, it sounds reasonable and shouldn't break anything.

**Comment by eLvErDe** [comment]
Yep, and my frontends guys will love it ;-)
