### ISSUE TITLE
"Bare functions are deprecated"  DeprecationWarning when using SwaggerFile router

### ISSUE THREAD

**Issue by walkingpendulum** [hh-h/aiohttp-swagger3#58]
### repro
swagger.yaml file
```yaml
openapi: 3.0.0
info:
  description: ''
  version: ''
  title: ''
paths:
  '/':
    get:
      responses:
        '200':
          description: ''
```
Test script
```python
import warnings

from aiohttp import web
from aiohttp_swagger3 import SwaggerFile, SwaggerUiSettings


async def hello(request):
    return web.Response(text="Hello, world")


if __name__ == '__main__':
    warnings.simplefilter('always')

    app = web.Application()
    router = SwaggerFile(
        app=app,
        spec_file="swagger.yaml",
        swagger_ui_settings=SwaggerUiSettings(path="/docs"),
    )

    router.add_routes([web.get('/', hello)])
    # web.run_app(app)
```
### Output
```
/Users/walkingpendulum/test/venv/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py:152: 
DeprecationWarning: Bare functions are deprecated, use async ones
  "use async ones", DeprecationWarning)
```

### versions 
```
aiohttp-swagger3==0.4.3
aiohttp==3.6.2
```
Python 3.7

### extra
https://github.com/aio-libs/aiohttp/issues/3252 contains some discussion on this topic. 

### proposed solution
To get rid of `partial` call here in favor of custom tailored `async def` wrapper.

**Comment by hh-h** [comment]
Hey, care to send a PR?

**Comment by walkingpendulum** [comment]
sure. I know nothing about estimates but one day for sure :)

**Comment by hh-h** [comment]
I did some research, actually, it is fixed in master, but not in 3.7. What the purpose of this issue? Do you think it is a some performance issue or you just don't like the warning itself?

**Comment by walkingpendulum** [comment]
> it is fixed in master, but not in 3.7
what does it mean? master of what repo? 

> Do you think it is a some performance issue or you just don't like the warning itself?
the latter. this message in logs is to warn me that something may change in future and everything will breaks. I just trying to take care of it.

**Comment by hh-h** [comment]
> what does it mean? master of what repo?

I mean the aiohttp repo, it uses [iscoroutinefunction](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_urldispatcher.py#L137) and its implementation checks for partial, see [here](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L109). See docs for python 3.8 [here](https://docs.python.org/3/library/inspect.html#inspect.iscoroutinefunction)

> something may change in future and everything will breaks. I just trying to take care of it.

Then don't worry, aiohttp version is pinned, I don't think the new version will be released without successful tests :)

Feel free to close the issue.

**Comment by walkingpendulum** [comment]
well, I should have guessed to look up in python docs :) although I saw comment of asvetlov about introspection-level bug here...
thanks for research you've done
