### ISSUE TITLE
readOnly support ?

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#59]
Hi,

I see you have readOnly prop support in.yout TODO list. I'd would love to have it ;-)

Thanks

**Comment by eLvErDe** [comment]
Obvious use case:

"id" field generated by backend, returned on GET, can't be set with POST/PUT

**Comment by hh-h** [comment]
Hey, TBH it's not going to happened in the nearest future. The juice is not worth the squeeze. I'll leave it open, tho.

**Comment by eLvErDe** [comment]
No problem. How do you handle this in your projects ? For the moment I usually make two different schemas but I'll probably starting a big project soon and having this would save me a lot of duplicate definitions

**Comment by hh-h** [comment]
We have a big project, more than 100 routes. We use either Request/Response{ENTITY_NAME} OR {ENTITY_NAME}Input/Output. Yes, it is produces some copy&pasta, unfortunately. But sometimes we have really different schemas that `readOnly` wouldn't help.

**Comment by eLvErDe** [comment]
BtW there's writeOnly too, but IMHO it's less useful.
