### ISSUE TITLE
add authentication

### ISSUE THREAD

**Issue by palko444** [hh-h/aiohttp-swagger3#6]
Hello,

can you please add also authorization/authentication?
https://swagger.io/docs/specification/authentication/

Thank you in advance

**Comment by hh-h** [comment]
Hi, can you provide some details? What type of A/A do you use in your project? What do you expect from library? Also provide swagger spec file if possible.
Thank you.

**Comment by hh-h** [comment]
Please, check this out https://github.com/hh-h/aiohttp-swagger3/blob/master/examples/authentication/main.py
