### ISSUE TITLE
Is there a way to generate one big swagger YAML from entire applicaiton ?

### ISSUE THREAD

**Issue by socketpair** [hh-h/aiohttp-swagger3#61]
So, it will be nice to have such functionality to build automatic documentation, and also to generate client library

**Comment by hh-h** [comment]
No, I'm afraid there's no such functionality, but you can try to download swagger.json (`/docs/swagger.json`) and convert it to YAML.

**Comment by jschmidtnj** [comment]
for future readers, I did something like this:

```python3
from aiohttp_swagger3.routes import _SWAGGER_SPECIFICATION as swaggerspec_key
from yaml import dump as yaml_dump
from json import dumps as json_dump, loads as json_load

swagger_spec_dict = json_load(json_dump(app[swaggerspec_key], cls=CustomEncoder))
swagger_spec_file_path = './spec.yml'
with open(swagger_spec_file_path, 'w') as swagger_spec_file:
        yaml_dump(swagger_spec_dict, swagger_spec_file)
```

note this isn't ideal because I'm dumping and then loading the string again. couldn't figure out a way around that...
