### ISSUE TITLE
RegExp in route

### ISSUE THREAD

**Issue by santasdi** [hh-h/aiohttp-swagger3#62]
If regular expression is situated in route path, swagger don't pass parameter to route.
For example, route path is```/pets/{id}``` without reg.exp. Url of request with ```id=123``` and GET method will be ```http://127.0.0.1:8080/api/v1/pets/123``` and it's all OK, but if route path look like ```/pets/{id: \d+}```, where ```\d+``` is one or more integers then url of request will be looking like ```http://127.0.0.1:8080/api/v1/pets/{id:\d+}``` and it return 404 error in my handler.

**Comment by hh-h** [comment]
Are you talking about "Try it" button in swagger UI?

**Comment by santasdi** [comment]
Yes, about it.

**Comment by hh-h** [comment]
This is a third-party library, I don't support it.

**Comment by santasdi** [comment]
Thank you for rapid answer. Have a nice day.
