### ISSUE TITLE
How to handle route prefix rewrite?

### ISSUE THREAD

**Issue by mykola-mokhnach** [hh-h/aiohttp-swagger3#66]
Hello,

this is, probably, a question, but could also be a feature request.

When we publish our API endpoints to Swagger then there is an issue with route prefixes. E.g. our APIs routes in the code look like `/api/v1/service/...`, but they are exposed to the external world via an API Gateway, which rewrites all paths to the following form `/v1/service` (the `/api` part is cut off). How it would be possible to represent that in the resulting Swagger spec, so the public OpenApi sandbox page behind the API Gateway points to the correct paths (starting with `/v1/service` rather than `/api/v1/service`)?

**Comment by hh-h** [comment]
Sorry, but this request is beyond this library responsibility.

Only one thing I can suggest is to register both routes `/v1/service` and `/api/v1/service`...

**Comment by mykola-mokhnach** [comment]
> Only one thing I can suggest is to register both routes /v1/service and /api/v1/service to the same handler.

Thanks, we'll do that
