### ISSUE TITLE
Re-use validation schema for marshalling ?

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#67]
Hello hh,

Do you think its possible to re-use the validation schema for response marshalling ? As a replacement for marshmallow ?

Regards

**Comment by hh-h** [comment]
Hi, I'm not sure I follow your question. Could you provide some examples?

**Comment by eLvErDe** [comment]
Hello,

Yes sure. Imagine I have a POST payload defining an object "MyBodyPayload". Your module will take care of cleaning unwant keys from JSON payload and raising an error if the payload is not suitable.
Now from a GET route, I also returned a payload that should match MyBodyPayload. I'd like to re-use the same validation to ensure my actual replies matches this schema.

**Comment by hh-h** [comment]
Hi,

I wanted to add it at first but decided not to because this library is not designed for that.

Cheers!

**Comment by eLvErDe** [comment]
Oh okay, keep it in mind if you're making so refactoring one day :-)
