### ISSUE TITLE
fix usage with with aiohttp 3.7

### ISSUE THREAD

**Issue by RCheese** [hh-h/aiohttp-swagger3#68]
subj

**Comment by hh-h** [comment]
Please, provide some details.

**Comment by RCheese** [comment]
Version of aiohttp pinned in requirements.txt on <3.7
But I don't see reason for make it.
3.6 and 3.7 is compatible versions

**Comment by hh-h** [comment]
In a perfect world - yes it is, but in real-world it is better to check first because a delayed release is better than a broken library. I will release the new version at the weekend.
