### ISSUE TITLE
Inject custom YAML to route ?

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#70]
Hello,

I've been struggling with a not so hard but specific need. I want to create multiple routes attaching the same handler, however, I need to inject a bit of logic in the YAML OpenAPI docstring for each route.
Is that possible ? I tried to hack around with a decorator modifying func `__doc__` (in the hope you're code will read the function definition after the decorator) but as soon as I add a decorator to the handler, the route is not added to Swagger definition anymore (but still works if called directly).

Any pointer would be appreciated !

Regards, Adam.

**Comment by hh-h** [comment]
Hi,

I'm not sure about it, but here you go... The problem is that handlers registering after `run_app` is called, so you have to create a copy of your handler, something like that
```python
def mod(fn, what, to):
    new_fn = types.FunctionType(
        fn.__code__,
        fn.__globals__,
        name=fn.__name__,
        argdefs=fn.__defaults__,
        closure=fn.__closure__,
    )
    new_fn = functools.update_wrapper(new_fn, fn)
    new_fn.__kwdefaults__ = fn.__kwdefaults__
    new_fn.__doc__ = fn.__doc__.replace(what, to)
    return new_fn
```
and use it
```
web.post('/testtt1', mod(test_handler, 'CX', 'PX')),
web.post('/testtt2', mod(test_handler, 'CX', 'DX')),
web.post('/testtt3', mod(test_handler, 'CX', 'GX')),
web.post('/testtt4', mod(test_handler, 'CX', 'RX')),
```
but I strongly recommend not to use that :)

**Comment by eLvErDe** [comment]
Hello,

Thanks, that's pretty low level !
I read about types module and that was what I would have been trying to do this morning, use a function as a template and create new function with modded __doc__ using types.

I understand this is pretty unusual but I have a short list of custom IDs, stored as objects instances with a lot of attributes and methods. Each one has a very specific enum of values for output and specific description and some of them can even implement a POST route and also have specific enum for input values (and associated description for each value).
I honestly think this is the best way, as I can enhance my object to provide as_openapi_schema retuning directly the swagger documentation.

What you think ?

Thanks !

**Comment by hh-h** [comment]
Sorry, but I think you're taking advantage of my kindness. I am available to perform tasks on an hourly basis, if you are interested - contacts in `setup.py` file. :)

**Comment by eLvErDe** [comment]
Hello,

No problem, I wasn't asking for any help, what you provided is already very cool :)

Thanks

**Comment by eLvErDe** [comment]
For the record, if someone want to use it in a class, just wrap the "generated function" like this:

```
return types.MethodType(new_fn, self)
```

I managed to do exactly what I wanted, thanks to your code snippet
