### ISSUE TITLE
Can't define parameters in Link Object

### ISSUE THREAD

**Issue by zoicsoftware** [hh-h/aiohttp-swagger3#77]
It seems to be impossible to define "parameters" for a Link Object in a handler response. For example, if I duplicate the getUser links example in the [swagger links example](https://swagger.io/docs/specification/links/#how), I get the following error:
```Exception: Invalid schema for handler 'create_user' POST /users - data.201 must be valid exactly by one of oneOf definition``` 

If I remove the "parameters" section then there is no longer an exception. However, in this case the link really isn't valid, or useful, anymore as you need to be able to indicate that the id in the response body should be used as a parameter for the getUser operation. 

I believe that lines 1584/1585 of [schema.json](https://github.com/hh-h/aiohttp-swagger3/blob/d6011637447ac0ffb185e85c49a77f7e31eb27dc/aiohttp_swagger3/schema/schema.json#L1584) are the cause of this. These lines are:
```javascript 
"parameters": {
      "type": "object",
      "additionalProperties": {
      }
 },
```
By having an empty additionalProperties key, its invalid to have any properties inside of parameters.

**Comment by zoicsoftware** [comment]
#78  - Linking in pull request to remove the empty additionalProperties object.

**Comment by hh-h** [comment]
Hi, could you provide a reproducible example?

**Comment by zoicsoftware** [comment]
No problem. 

I pushed up a branch to my fork where I attempted to add a link to the docs_spec pet example between the create_pet and get_one_pet endpoints. 

[Here is the modified file](https://github.com/zoicsoftware/aiohttp-swagger3/blob/faad6328563475a932341c3a6823739e371a0144/examples/docs_spec/main.py#L68)

This results in the following error:
```python
Exception: Invalid schema for handler 'create_pet' POST /pets - data.201 must be valid exactly by one of oneOf definition
```

Here is the relevant changes that cause the error:
```python
async def create_pet(request: web.Request, body: Dict) -> web.Response:
    """
    some docs
    ---
    summary: Create a pet
    operationId: createPet
    tags:
      - pets
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              tag:
                type: string
    responses:
      '201':
        description: new pet
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
        links:
          GetPetById:
            operationId: getPet
            parameters:
              pet_id: '$response.body#/id'
    """
    # or access to body via request['data']['body']
    pet = PET_FACTORY.create(body["name"], body.get("tag"))
    request.app["storage"][pet["id"]] = pet
    return web.json_response(pet, status=201)


async def get_one_pet(request: web.Request, pet_id: int) -> web.Response:
    """
    ---
    summary: Info for a specific pet
    operationId: getPet
    tags:
      - pets
    parameters:
      - name: pet_id
        in: path
        required: true
        description: The id of the pet to retrieve
        schema:
          type: integer
          format: int32
    responses:
      '200':
        description: Expected response to a valid request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
    """
    if pet_id not in request.app["storage"]:
        raise web.HTTPNotFound()
    return web.json_response(request.app["storage"][pet_id])
```

**Comment by hh-h** [comment]
Thanks for the example. The spec is correct, the bug somewhere in parsing/validation, see
![image](https://user-images.githubusercontent.com/8166963/105812800-e0369d80-5fbf-11eb-9689-19455b6df726.png)
I'll investigate it at the weekend probably.

**Comment by hh-h** [comment]
https://github.com/horejsek/python-fastjsonschema/pull/110

**Comment by zoicsoftware** [comment]
@hh-h Thank you for working the fix with python-fastjsonschema and updating the dependency version. This appears to have fixed the problem with link parameters.

**Comment by hh-h** [comment]
I'm happy to help!
