### ISSUE TITLE
Correct openapi fails validation

### ISSUE THREAD

**Issue by aquamatthias** [hh-h/aiohttp-swagger3#91]
I use this library to show swagger-ui from my openapi doc, that is completely maintained in a file.
The file is attached and can be found here: [api-doc.yaml.zip](https://github.com/hh-h/aiohttp-swagger3/files/6701659/api-doc.yaml.zip).

Integration looks like this:
```python
        SwaggerFile(
            self.app,
            spec_file="./static/api-doc.yaml",
            swagger_ui_settings=SwaggerUiSettings(path="/api-doc", layout="BaseLayout")
        )
```

When the system is starting up, I get this error:
```
 File "/core/web/api.py", line 36, in __init__
    SwaggerFile(
  File "/env/lib/python3.9/site-packages/aiohttp_swagger3/swagger_file.py", line 45, in __init__
    super().__init__(
  File "/env/lib/python3.9/site-packages/aiohttp_swagger3/swagger.py", line 81, in __init__
    self.spec_validate(self.spec)
  File "<string>", line 63, in validate
  File "<string>", line 2230, in validate___definitions_paths
  File "<string>", line 390, in validate___definitions_pathitem
  File "<string>", line 480, in validate___definitions_operation
  File "<string>", line 564, in validate___definitions_responses
TypeError: expected string or bytes-like object
(env) 
```

The openapi doc looks correct to me - editor.swagger.io does not complain.
I also checked the jsonschema via https://www.jsonschemavalidator.net.

I tried to avoid the validation via this PR https://github.com/hh-h/aiohttp-swagger3/pull/90
which does not seem to be the ideal solution.

Env:
Python 3.9.5
aiohttp[speedups]==3.7.4.post0
aiohttp-swagger3==0.6.0

**Comment by hh-h** [comment]
In json keys must be strings, but you use integers, see schema https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json#L945

replace 200 -> '200', etc in responses and it should work.

**Comment by aquamatthias** [comment]
@hh-h you are right - this fixes the issue. Sorry for the noise...

**Comment by hh-h** [comment]
That's fine. Unfortunately, `fastjsonschema` doesn't provide understandable error messages that can be confusing.
