### ISSUE TITLE
pytest DeprecationWarning: Bare functions are deprecated, use async ones

### ISSUE THREAD

**Issue by AustEcon** [hh-h/aiohttp-swagger3#95]
Hi I am just flagging a warning from pytest:

`...\Python310\lib\site-packages\aiohttp\web_urldispatcher.py:189: DeprecationWarning: Bare functions are deprecated, use async ones`

When I set a breakpoint in the relevant aiohttp library code I find it seems to be this function causing the warning:

`functools.partial(<bound method Swagger._handle_swagger_call of <aiohttp_swagger3.swagger_file.SwaggerFile object`

Is that a difficult one to fix?

It's not really bothering me but it's nice to stay ontop of these things if possible 😄

**Comment by hh-h** [comment]
Hi, what aiohttp version do you use?
