### ISSUE TITLE
Definitions with requestBody / required: false can not be used

### ISSUE THREAD

**Issue by hvraven** [hh-h/aiohttp-swagger3#97]
Schema with `requestBody` where `required` is set to false can not be used as the library fails to handle them.

The library first raises a 400 with a complaint about the content type `application/octet-stream` not being supported. I would already expect this to work, as it is the default for an empty body. When explicitly setting `application/json` the library fails with another 400 `Expecting value: line 1 column 1 (char 0)`.

Below a modification of `test_nullable_ref` test case from `test_docs_request_bodies` to reproduce the issue:

```python
async def test_non_required(swagger_docs_with_components, aiohttp_client):

    routes = web.RouteTableDef()

    @routes.post("/r")
    async def handler(request, body: Dict):
        """
        ---
        requestBody:
          required: false
          content:
            application/json:
              schema:
                type: object
                required:
                  - pet
                properties:
                  pet:
                    nullable: true
                    allOf:
                      - $ref: '#/components/schemas/Pet'

        responses:
          '200':
            description: OK.
        """
        return web.json_response(body)

    swagger = swagger_docs_with_components()
    swagger.add_routes(routes)

    client = await aiohttp_client(swagger._app)

    resp = await client.post("/r", headers={"content-type": "application/json"})
    assert resp.status == 200
    assert await resp.text() == ""

    body = {
        "pet": None,
    }
    resp = await client.post("/r", json=body)
    assert resp.status == 200
    assert await resp.json() == body

    body = {
        "pet": {
            "name": "lizzy",
            "age": 12,
        }
    }
    resp = await client.post("/r", json=body)
    assert resp.status == 200
    assert await resp.json() == body
```

**Comment by hh-h** [comment]
Valid function signature should be `Optional[Dict] = None` in this case.

**Comment by hvraven** [comment]
You're of course right, I missed that. It doesn't change anything on the observed behaviour.
It is also the same if I get the body from the request instead (using `await request.text()`)

**Comment by hh-h** [comment]
I'll check it out this weekend.

**Comment by hvraven** [comment]
Cool, thank you very much already (also for the library in general).
