### ISSUE TITLE
Adding licence info to spec isn't being recognized by the SwaggerDocs class.

### ISSUE THREAD

**Issue by aspenforest** [hh-h/aiohttp-swagger3#99]
Adding contact info by manually editing the swagger spec dictionary after the instantiation of the SwaggerDocs class works fine, but for some reason I can't understand why, the UI frontend does not display the license info at all. If one were to use SwaggerFile class with a separate spec.yaml file instead, the UI frontend will display the license info correctly. This behavior is perplexing for me, since both classes, SwaggerDocs and SwaggerFile, pass the spec dict to the parent Swagger class the same way. Source:

<pre>
from helpers import build_route_table
from aiohttp_swagger3 import SwaggerDocs, SwaggerUiSettings
from aiohttp import web

app = web.Application()  
swagger = SwaggerDocs(
    app, 
    swagger_ui_settings=SwaggerUiSettings(path="/")
)  
swagger.spec['info'] = {  
    'title': 'API Name',  
    'description': 'API Description',  
    'contact': {  
        'name': 'Creator Name',  
        'url': 'Website Address',  
        'email': 'Email Address'  
    },  
    'licence': {  
        'name': 'MIT License',  
        'url': 'Website Address'  
    },  
    'version': '1.0.0'  
}
routes = build_route_table()
swagger.add_routes(routes)
app['storage'] = dict()
web.run_app(
    app, 
    host='localhost', 
    port='8080'
)
</pre>

**Comment by hh-h** [comment]
`license` not `licence`.

I'll add these two fields (contact and license) to SwaggerDocs.

**Comment by hh-h** [comment]
see example https://github.com/hh-h/aiohttp-swagger3/blob/2dff6e34640255674a29f15015992c81ec033263/examples/custom_swagger_info/main.py
